# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2

  # Automatically find bugs and errors in your shell scripts with ShellCheck on every commit.
  # Add this static analysis tool to any CI/CD workflow and ShellCheck your scripts across your repository.
  shellcheck: circleci/shellcheck@2.2.4

  # Install a variety of browsers and tools for browser testing. Includes Chrome, FireFox, ChromeDriver and GeckoDriver.
  # Used for testing Chrome extension installation
  browser-tools: circleci/browser-tools@1.2.3

  # Detect bugs and vulnerabilities in your repository.
  sonarcloud: sonarsource/sonarcloud@1.1.0

  # A Chrome Web Store Manager.
  chrome-webstore: sugarshin/chrome-webstore@0.0.3

defaults: &defaults
  # Define a Node docker executor - https://circleci.com/developer/images/image/cimg/node
  docker:
    - image: cimg/node:17.1-browsers
  resource_class: large

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Install the dependencies from a package.json and cache them for faster future runs
      - node/install-packages:
          pkg-manager: npm
          include-branch-in-cache-key: false

      # Run build command
      - run:
          name: "Build"
          command: npm run build

      # Zip the build folder to create a Chrome extension package
      - run:
          name: "Zip package"
          command: (cd dist && zip -r ../build.zip . && cd ..)

      # Store the build result as an artefact
      - store_artifacts:
          path: build.zip

      # Persist the build result for further steps
      - persist_to_workspace:
          root: .
          paths:
            - build.zip

  test:
    <<: *defaults
    parallelism: 5

    steps:
      # Install Chrome browser
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
            node --version
          name: Check install

      - checkout

      # Install the dependencies from a package.json and cache them for faster future runs
      - node/install-packages:
          pkg-manager: npm
          include-branch-in-cache-key: false

      # Run tests in parallel, split by timing
      - run:
          name: Run tests
          command: |
            TESTS=$(circleci tests glob "src/app/**/*.spec.ts" | circleci tests split --split-by=timings)
            ARGS=(); for TEST in $TESTS; do ARGS+=" --include "; ARGS+=$TEST; done;
            npm run test -- ${ARGS[@]}

      # Store test results
      - store_test_results:
          path: junit
      - store_artifacts:
          path: ~/junit

      # Persist the code coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage/YA2TM/lcov.info

  sonar:
    docker:
      - image: cimg/node:17.1

    steps:
      # Checkout the code as the first step.
      - checkout

      # Attach the build result build.zip
      - attach_workspace:
          at: .

      # Run sonar scan
      - sonarcloud/scan

  publish:
    docker:
      - image: cimg/node:17.1

    steps:
      # Checkout the code as the first step.
      - checkout

      # Install the dependencies from a package.json and cache them for faster future runs
      - node/install-packages:
          pkg-manager: npm
          include-branch-in-cache-key: false

      # Attach the build result build.zip
      - attach_workspace:
          at: .

      # Publish the zip file to the Chrome Web Store Developer Dashboard
      - run:
          name: "Publish to the Google Chrome Store"
          command: $(npm bin)/chrome-webstore-upload upload --source build.zip --auto-publish

workflows:
  version: 2
  main:
    jobs:
      - shellcheck/check
      - build
      - test:
          context: SonarCloud
      - sonar:
          context: SonarCloud
          requires:
            - test
      - publish:
          requires:
            - shellcheck/check
            - test
            - build
          filters:
            branches:
              only:
                - main
